---
  clickhouse:
    hosts:
      clickhouse-01:
        ansible_host: 51.250.10.112
        ansible_ssh_user: egor
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  vector:
    hosts:
      vector-01:
        ansible_host: 84.201.128.39
        ansible_user: egor
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  lighthouse:
    hosts:
      lighthouse-01:
        ansible_host: 130.193.49.24
        ansible_user: egor
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
